import type { Metadata } from 'next'
import { ClerkLoaded, ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { auth } from '@clerk/nextjs/server'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

const ProviderWrapper = async ({ children }: { children: React.ReactNode }) => {
  const a = await auth()

  if (!a.userId) return children

  // Add your proivders from SignedInApp here
  return (
    <div>
      {children}
    </div>
  )
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const a = await auth()
  return (
    <ClerkProvider appearance={{
      cssLayerName: 'clerk'
    }}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ClerkLoaded>
            <header className="flex content-between flex-row p-8">
              <ul className="flex flex-row gap-8 grow">
                <li><Link href="/">Home</Link></li>
                <li><Link href="/product-maodals">Products</Link></li>
              </ul>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <div className="flex flex-row gap-8">
                  <span>{a.userId}</span>

                  <UserButton />
                </div>
              </SignedIn>
            </header>
          </ClerkLoaded>
          <ProviderWrapper>
            {children}
          </ProviderWrapper>
        </body>
      </html>
    </ClerkProvider>
  )
}
